<a href="https://colab.research.google.com/github/AndreAntonioCampos/FIAP_POS/blob/main/FASE_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FASE 2 - AULA 1 e 2 - BIBLIOTECAS FUNDAMENTAIS E PRIMEIROS PASSOS EM ML

In [ ]:
#Comando para instalar a bilbioteca do Pandas
!pip install pandas

IMPORTANDO O PANDAS

In [ ]:
#Importar a biblioteca do Pandas
import pandas as pd

IMPORTANDO UM ARQUIVO NO FORMATO EXCEL



In [ ]:
#dataframe = pd.read_excel("nome_arquivo.xlsx","sheet_name="nome_aba")
df_excel = pd.read_excel("Chess.xlsx", sheet_name="Chess")

In [ ]:
#Lendo o Excel
df_excel.head()

rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3  
4         C41                        Philidor Defense            5

IMPORTANDO UM ARQUIVO NO FORMATO CSV

In [ ]:
#dataframe = ped.read_csv("nome_arquivo.csv", sep="delimitador")
df_csv = pd.read_csv("Tomato.csv", sep=",")

In [ ]:
#Visualizar os ultimos dados do df
df_csv.tail()

Date Unit  Minimum  Maximum  Average  Market
2736  2021-05-09   Kg       10       15     12.5  Tomato
2737  2021-05-10   Kg       10       15     12.5  Tomato
2738  2021-05-11   Kg       10       15     12.5  Tomato
2739  2021-05-12   Kg       30       35     32.5  Tomato
2740  2021-05-13   Kg       35       40     37.5  Tomato

SABER O TOTAL DE LINHAS E COLINAS DO DF

In [ ]:
#linhas, colunas lembrando que contem o titulo
df_csv.shape

(2741, 6)

SABER O RESUMO DA MINHA BASE DE DADOS

In [ ]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   rated           20058 non-null  bool   
 1   created_at      20058 non-null  float64
 2   last_move_at    20058 non-null  float64
 3   turns           20058 non-null  int64  
 4   victory_status  20058 non-null  object 
 5   winner          20058 non-null  object 
 6   increment_code  20058 non-null  object 
 7   white_id        20058 non-null  object 
 8   white_rating    20058 non-null  int64  
 9   black_id        20058 non-null  object 
 10  black_rating    20058 non-null  int64  
 11  opening_eco     20058 non-null  object 
 12  opening_name    20058 non-null  object 
 13  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(7)
memory usage: 2.0+ MB


VISÃO DESCRITIVA DA BASE DE DADOS

In [ ]:
df_csv.describe()

Minimum      Maximum      Average
count  2741.000000  2741.000000  2741.000000
mean     35.089748    41.281284    38.185516
std      16.648425    17.364135    16.970949
min       8.000000    12.000000    10.000000
25%      22.000000    30.000000    25.000000
50%      30.000000    38.000000    35.000000
75%      45.000000    50.000000    47.500000
max     115.000000   120.000000   117.500000

POSSO TRANSPOR OD DADOS, SOMENTE COLOCANDO UM T AO FINAL DO CÓDIGO

In [ ]:
df_csv.describe().T

count       mean        std   min   25%   50%   75%    max
Minimum  2741.0  35.089748  16.648425   8.0  22.0  30.0  45.0  115.0
Maximum  2741.0  41.281284  17.364135  12.0  30.0  38.0  50.0  120.0
Average  2741.0  38.185516  16.970949  10.0  25.0  35.0  47.5  117.5

PARA ANALISAR UMA COLUNA ESPECIFICA DA BASE

In [ ]:
#É possivel saber quais informações possuem nesta coluna, pra não precisar varrer toda a base de dados com head, tail
#set(df["coluna"])
set(df_excel["victory_status"])

{'draw', 'mate', 'outoftime', 'resign'}

CRIAR NOVOS VALORES E ARMAZENAR DENTRO DAS COLUNAS

Fazer uma nova variavel, criando uma função

Criar uma função def para categorizar os tomates e depois incluir essa informação na minha base de dados

In [ ]:
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [ ]:
#def = função da variavel
#categorizar_tomate_media = nome da minha função
#(media) a coluna
#if = se
#elis = um segundo se
#else = Se não achar o if ou elif
#return = Valor que vai retornar na minha variavel

def categorizar_tomate_media(media):
  if media >=40 and media <=70:
    return "tomate medio"
  elif media <40:
    return "tomate pequeno"
  else:
    return "tomatão"

In [ ]:
#CRIAR A NOVA COLUNA
#df["coluna que vou criar"] = df["por qual coluna faz a leitura para aplicar"].apply(a função que criei)
df_csv["categoria_tomate"] = df_csv["Average"].apply(categorizar_tomate_media)

In [ ]:
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market categoria_tomate
0  2013-06-16   Kg       26       32     29.0  Tomato   tomate pequeno
1  2013-06-17   Kg       20       25     22.5  Tomato   tomate pequeno
2  2013-06-18   Kg       22       26     24.0  Tomato   tomate pequeno
3  2013-06-19   Kg       24       28     26.0  Tomato   tomate pequeno
4  2013-06-20   Kg       22       26     24.0  Tomato   tomate pequeno

In [ ]:
#Para ver a média de acordo com uma coluna usando o describe()
#groupby = agrupar por
#(["categoria_tomate"]) = informando o nome da coluna
#describe() = função para ver a média

df_csv.groupby(["categoria_tomate"]).describe()

Minimum                                                      \
                   count       mean       std   min   25%   50%   75%    max   
categoria_tomate                                                               
tomate medio       954.0  47.818658  8.203065  30.0  40.0  45.0  55.0   65.0   
tomate pequeno    1638.0  23.978022  7.175572   8.0  18.0  25.0  30.0   38.0   
tomatão            149.0  75.744966  7.324666  65.0  70.0  75.0  80.0  115.0   

                 Maximum             ...              Average             \
                   count       mean  ...   75%    max   count       mean   
categoria_tomate                     ...                                   
tomate medio       954.0  55.009434  ...  60.0   75.0   954.0  51.414046   
tomate pequeno    1638.0  29.528694  ...  35.0   44.0  1638.0  26.753358   
tomatão            149.0  82.583893  ...  85.0  120.0   149.0  79.164430   

                                                           
                       std   min   25%   50%   75%    max  
categoria_tomate                                           
tomate medio      8.272792  40.0  45.0  50.0  57.5   70.0  
tomate pequeno    7.191735  10.0  21.5  27.5  32.5   39.5  
tomatão           7.367396  70.5  75.0  77.5  82.5  117.5  

[3 rows x 24 columns]

FILTRAR OS DADOS

Usamos o .loc


In [ ]:
#variavel_de_filtro = df["coluna que quero aplicar o filtro"] condição
#df.loc[variavel_de_filtro]

filtro = df_csv["Average"] < 40
df_csv.loc[filtro]

Date Unit  Minimum  Maximum  Average  Market categoria_tomate
0     2013-06-16   Kg       26       32     29.0  Tomato   tomate pequeno
1     2013-06-17   Kg       20       25     22.5  Tomato   tomate pequeno
2     2013-06-18   Kg       22       26     24.0  Tomato   tomate pequeno
3     2013-06-19   Kg       24       28     26.0  Tomato   tomate pequeno
4     2013-06-20   Kg       22       26     24.0  Tomato   tomate pequeno
...          ...  ...      ...      ...      ...     ...              ...
2736  2021-05-09   Kg       10       15     12.5  Tomato   tomate pequeno
2737  2021-05-10   Kg       10       15     12.5  Tomato   tomate pequeno
2738  2021-05-11   Kg       10       15     12.5  Tomato   tomate pequeno
2739  2021-05-12   Kg       30       35     32.5  Tomato   tomate pequeno
2740  2021-05-13   Kg       35       40     37.5  Tomato   tomate pequeno

[1638 rows x 7 columns]

FASE 2 - AULA 3 - BIBLIOTECAS FUNDAMENTAIS E PRIMEIROS PASSOS EM ML

BIBLIOTECA NUMPY

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
#Criei uma lista
arr_list = np.array([1,2,3,4,5])
print(arr_list)

[1 2 3 4 5]


CRIAR UMA MATRIZ PARA CASOS DE BASES QUE VENHAM COM VALORES VAZIOS

In [ ]:
#criei uma matriz de zero com 4 linhas e 6 colunas
arr_zero = np.zeros((4,6))
print(arr_zero)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#criei uma matriz de zero com 3 linhas e 4 colunas
arr_one = np.ones((3,4))
print(arr_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Pra preencher com valores aleatórios de 0 a 1
arr_random = np.random.rand(3,4)
print(arr_random)

[[0.71106717 0.09715829 0.12593768 0.86163591]
 [0.89492618 0.93328954 0.10219418 0.58821991]
 [0.4267158  0.6884974  0.21573771 0.94109985]]


In [ ]:
#ANALISE DA DIMENSÃO DO DADO PARA ENTENDER O FORMATO, DIMENSÃO
print(arr_random.shape)

(3, 4)


In [ ]:
#Mudar a forma que meu array foi constuido, estou trocando para 3 colunas e 4 linhas
arr_randow_reshaped = arr_random.reshape(4,3)
print(arr_randow_reshaped)


[[0.71106717 0.09715829 0.12593768]
 [0.86163591 0.89492618 0.93328954]
 [0.10219418 0.58821991 0.4267158 ]
 [0.6884974  0.21573771 0.94109985]]
